version: '3.8'

services:
  backend:
    restart: always
    # Remove development volumes
    volumes:
      - ./data:/app/data
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G

  frontend:
    restart: always
    # Remove development volumes
    volumes: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    # Use production build variables if needed
    environment:
      - REACT_APP_API_URL=/api  # Assuming API is proxied through Nginx
      
  # Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M 