version: '3.8'

services:
  backend:
    restart: always
    # Remove development volumes
    volumes:
      - ./data:/app/data
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  frontend:
    restart: always
    # Remove development volumes
    volumes: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    # Use production build variables if needed
    environment:
      - REACT_APP_API_URL=/api  # Assuming API is proxied through Nginx
      
  # Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/cache:/var/cache/nginx
    depends_on:
      - backend
      - frontend
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 60s
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3 